### ISSUE TITLE
use same code for snapsets and non-snapset arguments

### ISSUE THREAD

**Issue by richm** [linux-system-roles/snapshot#44]
There is a lot of slightly duplicated code for managing snapsets and for managing arguments that are not snapsets.  We should instead figure out a way to unify this code.  One way would be to create a pseudo snapset from non-snapset arguments.

**Comment by richm** [comment]
Also related - use the same code for `verify` and non-verify - in some cases the code does almost the same thing with slight differences.  also note that `verify` is a lot like Ansible check mode.

**Comment by trgill** [comment]
I'll update to remove the duplicated code.

I was thinking it would make sense to build a dict() of LVs to snapshot from either the JSON or the parameters.  Then pass the dict to a common function.

It might make sense to return errors as a dict too?  Not sure.

FYI - I'm working on this before https://github.com/linux-system-roles/snapshot/issues/43

**Comment by richm** [comment]
> I'll update to remove the duplicated code.
> 
> I was thinking it would make sense to build a dict() of LVs to snapshot from either the JSON or the parameters. Then pass the dict to a common function.
> 
> It might make sense to return errors as a dict too? Not sure.

Something like that, in order to do https://github.com/linux-system-roles/snapshot/issues/45

> 
> FYI - I'm working on this before #43

**Comment by richm** [comment]
done
